config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'events#index'
  resources :events do
    resources :event_attendees, only: [:new, :create, :destroy]
  end
  resources :users, only: [:show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 1000}
  validates :location, presence: true, length: { maximum: 200 }
  validates :date, presence: true, comparison: { greater_than_or_equal_to: Date.today }
  # Users may omit start_time / finish_time and may have events start after they finish
  # (to handle case where event begins at 11pm and finishes at 1am)

  belongs_to :creator, class_name: "User"
  # Has-many attendees :through event_attendees table
  has_many :event_attendees, foreign_key: :attending_event_id
  has_many :attendees, through: :event_attendees, source: :user

  # Using Scopes
  scope :past, -> { where('date < ?', Date.today) }
  scope :future, -> { where('date >= ?', Date.today) }

  # Using Class methods
  # def self.past
  #   where('date < ?', Date.today)
  # end

  # def self.future
  #   where('date >= ?', Date.today)
  # end
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event, foreign_key: :attending_event_id
  belongs_to :user, foreign_key: :event_attendee_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, foreign_key: :creator_id, class_name: "Event"

  # Has_many :attending_events through event_attendees table
  has_many :event_attendees, foreign_key: :event_attendee_id
  has_many :attending_events, through: :event_attendees, source: :event
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  before_action :configure_permitted_parameters, if:  :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :authenticate_user!

  def new
    @event_attendee = EventAttendee.new
  end

  def create
    @event = Event.find(params[:event_id])

    if @event.attendee_ids.include?(current_user.id) || @event.date < Date.today
      render "events/show", status: :unprocessable_entity
    else
      @event_attendee = @event.event_attendees.create(event_attendee_id: current_user.id)
      if @event_attendee.save
        redirect_back_or_to root_path
      else
        render "events/show", status: :unprocessable_entity
      end
    end
  end

  def destroy
    EventAttendee.where(event_attendee_id: current_user.id, attending_event_id: params[:event_id]).destroy_all
    redirect_back_or_to root_path
  end

  private

    def event_attendee_params
      params.require(:event_attendee).permit(:event_attendee_id, :attending_event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # @events = Event.all
    @past_events = Event.all.past.order(date: 'DESC')
    @future_events = Event.all.future.order(date: 'ASC')
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to action: "show", id: @event.id
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params) && @event.creator.id == current_user.id
      redirect_to event_url(@event)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.creator.id == current_user.id
      @event.event_attendees.clear
      @event.destroy!
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def event_params
    params.require(:event).permit(:title, :description, :location, :date, :start_time, :finish_time, :creator_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @created_events = current_user.created_events.all.order(created_at: 'DESC')
    @attending_events = current_user.attending_events.order(date: 'ASC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.erb
<div class="card mx-auto my-3 p-2" style="width: auto">
  <div class="card-header">
    <h5><%= link_to event.title, event_path(event.id), class: "card-title" %></h5>
  </div>
  <div class="card-body">
    <h6 class="card-subtitle"><%= event.date.to_fs(:short) %> | <%= event.start_time.to_fs(:time) %></h6>
    <p class="card-text"><%= event.location %></p>
  </div>
  <div class="card-footer">
    <p class="card-text"><%= event.description%></p>
    <% if user_signed_in? && event.creator.id == current_user.id %>
      <p class="card-text">Organiser: <em>You!</em></p>
    <% else %>
      <p class="card-text">Organiser: <%= event.creator.name %> (<%= event.creator.email %>)</p>
    <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<div class="container">
  <%= form_with model: event do |form| %>
    <div class="mb-3">
      <%= form.label :title, "Name of your event", class: "form-label" %>
      <%= form.text_field :title, class: "form-control", placeholder: event.title %>
    </div>
    <div class="mb-3">
      <%= form.label :description, "Description", class: "form-label" %>
      <%= form.text_area :description, rows: 5, cols: 50, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :location, "Location", class: "form-label" %>
      <%= form.text_field :location, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :date, "Date", class: "form-label" %>
      <%= form.date_field :date, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :start_time, "Start time", class: "form-label" %>
      <%= form.time_field :start_time, ampm: true, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :finish_time, "Finish time", class: "form-label" %>
      <%= form.time_field :finish_time, ampm: true, class: "form-control" %>
    </div>
    <div>
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1 class="p-2">All Events</h1>
<h2 class="p-2">Upcoming Events</h2>
<div class="container">
  <%= render @future_events %>
</div>
<h2 class="p-2">Past Events</h2>
<div class="container">
  <%= render @past_events %>
</div>

app/views/events/new.html.erb
<h1>Create a new event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
  <div class="container-fluid py-1">
    <h1 class="display-5 fw-bold"><%= @event.title %></h1>
    <div class="col-md-8">
      <p class="lead">
        <p class="fs-3"><%= @event.location%></P>
        <p class="fs-5"><%= @event.date.to_fs(:short)%>, <%= @event.start_time.to_fs(:time)%> - <%= @event.finish_time.to_fs(:time)%></P>
      </p>
      <p><%= @event.description%></p>
      <p class="fs-5">Organiser: <%= @event.creator.name %> (<%= @event.creator.email%>)</p>
      <% if @event.date < Date.today %>
        <p><em>This event has already finished.</em></p>
      <% elsif user_signed_in? && @event.attendee_ids.include?(current_user.id) %>
        <p><em>You are registered to attend this event.</em></p>
        <%= link_to "Cancel your registration", event_event_attendee_path(@event), data: { turbo_method: :delete }, class: "btn btn-danger mb-3" %>
      <% else %>
        <%= form_with model: [ @event, @event.event_attendees.build ] do |form| %>
          <% form.text_field :attending_event_id, value: @event.id %>
          <%= form.submit "I'll be there!", class: "btn btn-primary" %>
        <% end %>
      <% end %>
      </br>
      <p>Who is attending:</p>
      <ul>
        <% @event.attendees.each do |attendee| %>
          <li><%= attendee.name %> (<%= attendee.email %>)</li>
        <% end %>
      </ul>
      <% if @event.creator.id == current_user.id %>
        <%= link_to "Edit Event", edit_event_path(@event), class: "btn btn-secondary mb-3" %>
        <%= link_to "Delete Event", @event, data: { turbo_method: :delete }, class: "btn btn-danger mb-3"%>
      <% end %>

    </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Events", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Your Events", user_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Event", new_event_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Odin Private Events</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <% if notice || alert %>
      <div class="container">
        <p class="alert alert-primary"><%= notice %></p>
        <p class="alert alert-secondary"><%= alert %></p>
      </div>
    <% else%>
      <br/>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<h1 class="p-2">Your Events</h1>
<% if @created_events.any? %>
  <h2 class="p-2">Organised by you:</h2>
  <div class="container">
    <%= render @created_events %>
  </div>
<% end %>
<h2 class="p-2">Your Upcoming Events</h2>
<div class="container">
  <% @attending_events.each do |event| %>
    <% if event.date >= Date.today %>
      <%= render event %>
    <% end %>
  <% end %>
</div>
<h2 class="p-2">Your Past Events</h2>
<div class="container">
  <% @attending_events.each do |event| %>
    <% if event.date < Date.today %>
      <%= render event %>
    <% end %>
  <% end %>
</div>